BuildMyResume/urls.py
"""BuildMyResume URL Configuration

The `urlpatterns` list routes URLs to views. 
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),

    path('home/', include(('home.urls', 'home'), namespace='home')),
    path('accounts/', include('allauth.urls')),

    path('signup/', users_views.signup, name='signup'),
    path('activate/<uidb64>/<token>/', users_views.activate, name='activate'),

    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('__debug__/', include('debug_toolbar.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
"""
home/urls.py

URLs for app_name: home
"""

from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('my-resume', views.my_resume, name='my-resume'),
    path('edit-profile/', views.edit_profile, name='edit-profile'),
    path('delete/<int:pk>.', views.delete_my_resume, name='delete-resume'),
    path('resume/create/', views.ResumeBucket.as_view(views.FORMS), name='create-resume'),
    path('edit/resume/<int:pk>/', views.ResumeBucket.as_view(views.FORMS), name='edit-resume'),
    path('templates/', views.templates, name='templates'),
    path('resume/<int:pk>/choose-template/', views.choose, name='choose'),
    path('resume/<int:pk>/view-resume/', views.choose, name='views-resume'),
]

home/models.py
from django.db import models

from .choices import LANGUAGE_PROFICIENCY_CHOICES, SKILL_PROFICIENCY_CHOICES, COURSEWORK_PROFICIENCY_CHOICES
from users.models import User


class ResumeMetaData(models.Model):
    resume_name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    
    def __str__(self):
        return f"{self.resume_name} | {self.user.username}"


class Experience(models.Model):
    resume = models.ForeignKey(ResumeMetaData, on_delete=models.CASCADE, blank=True)
    position = models.CharField(max_length=255, blank=True)
    company = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    description = models.TextField(max_length=1024, blank=True, null=True)
    
    def __str__(self):
        return self.position
    
    class Meta:
        verbose_name_plural = "Experience"
        ordering = ['-end_date', ]


class Education(models.Model):
    resume = models.ForeignKey(ResumeMetaData, on_delete=models.CASCADE, blank=True)
    school = models.CharField(max_length=255, blank=True)
    degree = models.CharField(max_length=255, blank=True)
    university = models.CharField(max_length=255, blank=True)
    major = models.CharField(max_length=255, blank=True)
    grade = models.FloatField(blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    
    def __str__(self):
        return self.school
    
    class Meta:
        verbose_name_plural = "Education"
        ordering = ['-end_date', ]


class Certificate(models.Model):
    resume = models.ForeignKey(ResumeMetaData, on_delete=models.CASCADE, blank=True)
    program_name = models.CharField(max_length=255, blank=True)
    platform_name = models.CharField(max_length=255, blank=True)
    issued_date = models.DateField(blank=True, null=True)
    certificate_id = models.CharField(max_length=255, blank=True, null=True)
    certificate_url = models.URLField(blank=True, null=True)
    
    def __str__(self):
        return self.platform_name

    class Meta:
        ordering = ['-issued_date', ]


class Skill(models.Model):
    resume = models.ForeignKey(ResumeMetaData, on_delete=models.CASCADE, blank=True)
    skill_name = models.CharField(max_length=255, blank=True)
    proficiency = models.IntegerField(choices=SKILL_PROFICIENCY_CHOICES, blank=True, null=True)
    
    def __str__(self):
        return self.skill_name


class Language(models.Model):
    resume = models.ForeignKey(ResumeMetaData, on_delete=models.CASCADE, blank=True)
    language_name = models.CharField(max_length=255, blank=True)
    proficiency = models.IntegerField(choices=LANGUAGE_PROFICIENCY_CHOICES, blank=True, null=True)
    
    def __str__(self):
        return self.language_name


class Coursework(models.Model):
    resume = models.ForeignKey(ResumeMetaData, on_delete=models.CASCADE, blank=True)
    coursework_name = models.CharField(max_length=255, blank=True)
    proficiency = models.IntegerField(choices=COURSEWORK_PROFICIENCY_CHOICES, blank=True, null=True)
    
    def __str__(self):
        return self.coursework_name


class Project(models.Model):
    resume = models.ForeignKey(ResumeMetaData, on_delete=models.CASCADE, blank=True)
    project_name = models.CharField(max_length=255, blank=True)
    stack_name = models.CharField(max_length=255, blank=True)
    project_link = models.URLField(blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    description = models.TextField(max_length=1024, blank=True, null=True)
    
    def __str__(self):
        return self.project_name

users/models.py
"""
users/models.py

:Models:
```UserManager```
```NewUSer```
"""

from django.contrib.auth.models import AbstractUser
from django.db import models
from django_resized import ResizedImageField


class User(AbstractUser):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    position = models.CharField(max_length=255, blank=True)
    phonenumber = models.CharField(max_length=255, blank=True)
    address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    country = models.CharField(max_length=255, blank=True)
    linkedin = models.URLField(blank=True, null=True)
    github = models.URLField(blank=True, null=True)
    bio = models.TextField(max_length=1024, blank=True, null=True)
    profile_picture = ResizedImageField(
        size=[300, 300],
        quality=100,
        default="profile_pics/default_profile.jpg",
        upload_to="profile_pics"
    )
    
    def __str__(self):
        return self.user.email

home/views.py
import logging

from xhtml2pdf import pisa

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.template.loader import get_template
from django.urls import reverse

from formtools.wizard.views import SessionWizardView

from users.forms import CustomUserChangeForm
from .forms import (ResumeForm, ProfileUpdateFrom, EducationFormSet, ExperienceFormSet, CertificateFormSet,  
                    SkillFormSet, LanguageFormSet, CourseworkFormSet, ChooseForm, ProjectFormSet)
from .models import ResumeMetaData, Experience, Education, Certificate, Skill, Language, Coursework, Project

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

FORMS = [
    ('resumes', ResumeForm),
    ('education', EducationFormSet),
    ('experience', ExperienceFormSet),
    ('certificates', CertificateFormSet),
    ('skills', SkillFormSet),
    ('languages', LanguageFormSet), 
    ('courseworks', CourseworkFormSet),
    ('projects', ProjectFormSet)
]

FORM_TYPES = ('education', 'experience', 'certificates', 'skills', 'languages', 'courseworks', 'projects',)

TEMPLATES = {
    'resumes': 'home/resumes.html',
    'education': 'home/education.html',
    'experience': 'home/experience.html',
    'certificates': 'home/certificates.html',
    'skills': 'home/skills.html',
    'languages': 'home/languages.html',
    'courseworks': 'home/courseworks.html',
    'projects': 'home/projects.html',
}


@login_required()
def choose(request, pk):
    user = request.user
    profile_picture_url = user.profile.profile_picture.url.strip('/')
    resume = ResumeMetaData.objects.get(pk=pk)
    form = ChooseForm(request.POST)
    template_path = ''
    
    if request.method == 'GET':
        form = ChooseForm()
    
    elif request.method == 'POST' and 'view-resume' in request.POST:
        if form.is_valid() and form.cleaned_data['resume_template'] == 'default':
            return render(request, 'home/default.html', {
                'form': form,
                'resume': resume,
                'profile_picture_url': profile_picture_url
            })
        
        elif form.is_valid() and form.cleaned_data['resume_template'] == 'simple':
            return render(request, 'home/simple.html', {
                'form': form,
                'resume': resume,
                'profile_picture_url': profile_picture_url
            })
    
    elif form.is_valid() and request.method == 'POST' and 'export-resume' in request.POST:
        
        if form.cleaned_data['resume_template'] == 'default':
            template_path = 'home/pdf_default.html'
        
        elif form.cleaned_data['resume_template'] == 'simple':
            template_path = 'home/pdf_simple.html'
            
        context = {'form': form, 'resume': resume, 'profile_picture_url': profile_picture_url}
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'filename="my_resume.pdf"'
        
        # find the template and render it.
        template = get_template(template_path)
        html = template.render(context)
        
        # create a pdf
        pisa_status = pisa.CreatePDF(html, dest=response)
        
        # if error then show some view
        if pisa_status.err:
            return HttpResponse(f'We had some errors <pre>{html}</pre>')
        return response
    
    return render(request, 'home/choose.html', {'form': form, 'resume': resume})


@login_required()
def my_resume(request):
    
    user = request.user
    resumes = ResumeMetaData.objects.filter(user=user).order_by('-created_at')
    
    return render(request, 'home/my_resumes.html', {'resumes': resumes})


@login_required()
def templates(request):
    
    return render(request, 'home/templates.html')


@login_required()
def edit_profile(request):
    
    if request.method == 'POST':
        user_form = CustomUserChangeForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateFrom(request.POST, request.FILES, instance=request.user.profile)
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Profile has been saved!")
            
            return HttpResponseRedirect(reverse('home:edit-profile'))
    
    else:
        user_form = CustomUserChangeForm(instance=request.user)
        profile_form = ProfileUpdateFrom(instance=request.user.profile)
    
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    
    return render(request, 'home/profile-edit.html', context)


@login_required()
def delete_my_resume(request, pk):
    
    resume = ResumeMetaData.objects.get(pk=pk)
    resume.delete()
    messages.success(request, "Resume is successfully deleted!")
    
    return HttpResponseRedirect(reverse('home:my-resume'))


def dict_has_data(input_dict):
    
    return any(input_dict[key] for key in input_dict)


class ResumeBucket(LoginRequiredMixin, SessionWizardView):
    login_url = '/login/'
    
    def get_form_initial(self, step):
        return {} if 'pk' in self.kwargs else self.initial_dict.get(step, {})
    
    def get_form_instance(self, step):
        if 'pk' in self.kwargs:
            pk = self.kwargs['pk']
            resume = ResumeMetaData.objects.get(id=pk)
            if step == 'resumes':
                return resume
            
            if step == 'education':
                return resume.education_set.all()
            
            if step == 'experience':
                return resume.experience_set.all()
            
            if step == 'certificates':
                return resume.certificate_set.all()
            
            if step == 'skills':
                return resume.skill_set.all()
            
            if step == 'languages':
                return resume.language_set.all()
            
            if step == 'courseworks':
                return resume.coursework_set.all()
            
            if step == 'projects':
                return resume.project_set.all()
        
        else:
            if step == 'resumes':
                return None
            
            if step == 'education':
                return Education.objects.none()
            
            if step == 'experience':
                return Experience.objects.none()
            
            if step == 'certificates':
                return Certificate.objects.none()
            
            if step == 'skills':
                return Skill.objects.none()
            
            if step == 'languages':
                return Language.objects.none()
            
            if step == 'courseworks':
                return Coursework.objects.none()
            
            if step == 'projects':
                return Project.objects.none()
        return None
    
    def get_template_names(self):
        
        return [TEMPLATES[self.steps.current]]
    
    def done(self, form_list, **kwargs):
        user = self.request.user
        resume_form_data = self.get_cleaned_data_for_step('resumes')
        resume_name = resume_form_data['resume_name']
        
        pk = self.kwargs['pk'] if 'pk' in self.kwargs else None
        
        resume, created = ResumeMetaData.objects.update_or_create(id=pk, defaults={
            'user': user, 'resume_name': resume_name
        })
        
        for form_name in FORM_TYPES:
            form_data_list = self.get_cleaned_data_for_step(form_name)
            for form_data in form_data_list:
                if not dict_has_data(form_data):
                    continue
                form_data['resume'] = resume
                
                form_instance = self.get_form(step=form_name)
                
                if obj := form_data.pop('id'):
                    form_instance.model.objects.filter(id=obj.id).update(**form_data)
                else:
                    form_instance.model.objects.create(**form_data)
        
        messages.add_message(self.request, messages.SUCCESS, message="Resume Saved!")
        
        return HttpResponseRedirect(reverse('home:my-resume'))

home/templates/home/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        
        <!--StyleSheets-->
        <link rel="stylesheet" href="{% static 'home/css/base.css' %}">

        <title>Build My Resume</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Hubballi&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@100&family=Source+Sans+Pro&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@500&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Syne+Mono&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">
    </head>

    <!--NAVBAR-->
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid cont">
            {% if user.is_authenticated %}
            <a class="navbar-brand" id="nav-title" href="{% url 'home' %}">Build<br>My Resume</a>
            {% else %}
            <a class="navbar-brand" id="nav-title" href="#">Build<br>My Resume</a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button> 
            
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                
                </ul>
                <span class="navbar-text">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link active" id="navbar-links" aria-current="page" href="{% url 'home:my-resume' %}">MyResume</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" id="navbar-links" aria-current="page" href="{% url 'home:edit-profile' %}">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" id="navbar-links" aria-current="page" href="{% url 'home:templates' %}">Templates</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" id="navbar-links" aria-current="page" href="{% url 'logout' %}">LogOut</a>
                            </li> 
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link active" id="navbar-links" aria-current="page" href="{% url 'login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" id="navbar-links" aria-current="page" href="{% url 'signup' %}">Sign Up</a>
                            </li>
                        {% endif %}
                        
                        
                    </ul>
                </span>
            </div>
        </div>
    </nav>

    <body>
        
        {% block content %}
          
        {% endblock content %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="" async defer></script>
    </body>

</html>

home/templates/home/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'home/css/base.css' %}">
        <link rel="stylesheet" href="{% static 'home/css/jquery-ui.css' %}">
        <link rel="stylesheet" href="{% static 'home/css/jquery-ui.min.css' %}">
        {% block style %}{% endblock style %}
        {% block title %}{% endblock title %}
    </head>
    <body>
        {% if messages %}
            <div class="messages">
                <ul class="messgaes">
                    {% for message in messages %}
                    <li {% if messages.tags %} class="{{ message.tags }} message-text"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <!--NAVBAR-->
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid cont">
                {% if user.is_authenticated %}
                <a class="navbar-brand" id="nav-title" href="{% url 'home' %}">Build<br>My Resume</a>
                {% else %}
                <a class="navbar-brand" id="nav-title" href="#">Build<br>My Resume</a>
                {% endif %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> 
                
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    
                    </ul>
                    <span class="navbar-text">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link active" id="navbar-links" aria-current="page" href="{% url 'home:my-resume' %}">MyResume</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" id="navbar-links" aria-current="page" href="{% url 'home:edit-profile' %}">Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" id="navbar-links" aria-current="page" href="{% url 'home:templates' %}">Templates</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" id="navbar-links" aria-current="page" href="{% url 'logout' %}">LogOut</a>
                                </li> 
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link active" id="navbar-links" aria-current="page" href="{% url 'login' %}">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" id="navbar-links" aria-current="page" href="{% url 'signup' %}">Sign Up</a>
                                </li>
                            {% endif %}
                            
                            
                        </ul>
                    </span>
                </div>
            </div>
        </nav>

        {% block subheader %}{% endblock subheader %}

        <div class="major-content">
            {% block popup %}{% endblock popup %}
            {% block content %}{% endblock content %}
        </div>
        
        <script src="{% static 'home/js/jquery-3.6.3.js' %}"></script>
        <script src="{% static 'home/js/jquery-ui.js' %}"></script>
        <script src="{% static 'home/js/jquery.formset.js' %}"></script>
        <script src="{% static 'home/js/script.js' %}"></script>
        <script src="" async defer type="text/javascript">

        </script>
        {% block script %}{% endblock script %}
    </body>
</html>

home/templates/home/home.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}

{% endblock content %}

home/templates/home/my_resumes.html
{% extends "home/base_layout.html" %}
{% load static %}
{% block title %}<title>BMR | MyResume</title>{% endblock title %}
{% block content %}
    <div class="resumes">
        {% for resume in resumes %}
            <div class="card mb-3 resume-card card" style="width: 500px;">
                <div class="container row g-0">
                    <div class="col-md-4">
                        <img src="{% static 'home/images/resume.png' %}" class="img-fluid rounded-start" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title resume-name">{{ resume.resume_name }}</h5>
                            <p class="card-text">Created On {{ resume.created_at }}</p>
                            <div class="delete-edit-view">
                                <a href="{% url 'home:delete-resume' pk=resume.id %}" class="delete-resume"><button>Delete</button></a>
                                <a href="{% url 'home:edit-resume' pk=resume.id %}" class="edit-resume"><button>Update</button></a>
                                <a href="{% url 'home:choose' pk=resume.id %}" class="view-resume"><button>View</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="empty-resume-bucket">
                <img src="{% static 'home/images/empty-folder.png' %}" class="centered">
                <p class="empty-resume-bucket-text"><b>You don't have any resumes</b></p>
            </div>
        {% endfor %}
    </div>
    <div class="create-resume-btn">
        <a href="{% url 'home:create-resume' %}"><button>Create Resume</button></a>
    </div>
{% endblock content %}

home/templates/home/profile-edit.html
{% extends "home/base_layout.html" %}
{% load static %}
{% block title %}<title>BMR | Profile</title>{% endblock %}

{% block content %}
<div class="card text-center profile-update-card">
    <form class="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-title">
            <h1>Profile</h1>
        </div>
        <div class="profile-image">
            <!-- {% if user.profile.profile_picture.url %}
                <img src="{% static 'user.profile.profile_picture.url' %}">
            {% else %} -->
                <!-- <img src="{% static 'media/profile_pics/default_profile.jpg' %}" id="user-img"> -->
            <!-- {% endif %} -->
        </div>
        <div class="profile-edit-form">
            <!--User Form-->
            <div class="form-floating mb-3">
                {{ user_form.first_name }}
                <label for="id_first_name" class="form_label">First Name</label>
            </div>
            <div class="form-floating mb-3">
                {{ user_form.last_name }}
                <label for="id_last_name" class="form_label">Last Name</label>
            </div>
            <!--Profile Form-->
            <div class="form-floating mb-3">
                {{ profile_form.position }}
                <label for="id_first_name" class="form_label">Position</label>
            </div>
            <div class="form-floating mb-3">
                {{ profile_form.address }}
                <label for="id_address" class="form_label">Address</label>
            </div>
            <div class="form-floating mb-3">
                {{ profile_form.city }}
                <label for="id_city" class="form_label">City</label>
            </div>
            <div class="form-floating mb-3">
                {{ profile_form.country }}
                <label for="id_country" class="form_label">Country</label>
            </div>
            <div class="form-floating mb-3">
                {{ profile_form.phonenumber }}
                <label for="id_phonenumber" class="form_label">Mobile Number</label>
            </div>
            <div class="form-floating mb-3">
                {{ profile_form.linkedin }}
                <label for="id_linkedin" class="form_label">LinkedIn</label>
            </div>
            <div class="form-floating mb-3">
                {{ profile_form.github }}
                <label for="id_github" class="form_label">GitHub</label>
            </div>
            <div class="form-floating mb-3">
                {{ profile_form.bio }}
                <label for="id_bio" class="form_label">Bio</label>
            </div>
            <div class="input-group mb-3">
                <input type="file" class="form-control" id="inputGroupFile02">
                <label class="input-group-text" for="inputGroupFile02">Upload</label>
            </div>
            <!-- {{ profile_form.profile_picture }} -->
        </div>
        <div class="profile-edit-form">
            <button type="submit" class="submit-button">Update/Save</button>
        </div>
    </form>
</div>


{% endblock content %}

home/templates/home/templates.html
{% extends "home/base_layout.html" %}
{% load static %}

{% block content %}

{% endblock content %}